from __future__ import annotations

from datetime import datetime, timezone
from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from apps.api.database import get_db
from apps.api.dependencies import get_current_user, get_optional_current_user
from apps.api.models import Job, User
from apps.api.schemas import JobSubmissionRequest
from apps.api.services.ats_alignment_service import (
    ATSAlignmentServiceError,
    calculate_ats_alignment,
    get_latest_ats_alignment,
)
from apps.api.services.eligibility_service import (
    evaluate_and_persist_job_eligibility,
)
from apps.api.services.gap_analysis.service import (
    GapAnalysisServiceError,
    generate_gap_analysis,
    get_latest_gap_analysis,
)
from apps.api.services.job_intelligence.service import (
    JobIntelligenceServiceError,
    generate_job_intelligence,
    get_latest_job_intelligence,
)
from apps.api.services.job_access import get_visible_job
from apps.api.services.job_listing import (
    SEARCH_TEXT_MAX_LENGTH,
    EmploymentTypeFilter,
    RemoteTypeFilter,
    job_listing_query,
)
from apps.api.services.job_match_service import (
    JobMatchServiceError,
    calculate_job_match as calculate_job_match_service,
    get_latest_job_match,
)
from apps.api.services.priority_ranking_service import (
    PriorityItem,
    PriorityRankingServiceError,
    build_job_priority,
)
from apps.api.services.requirement_intelligence.persistence_service import (
    RequirementIntelligencePersistenceError,
    generate_requirement_intelligence,
    get_latest_requirement_intelligence,
)
from apps.api.services.job_submission.service import (
    JobSubmissionServiceError,
    submit_job,
)
from apps.api.services.resume_improvement.contracts import (
    ResumeImprovementRequest,
)
from apps.api.services.resume_improvement.service import (
    ResumeImprovementServiceError,
    create_resume_improvement,
    get_latest_resume_improvement,
    run_recheck,
)
from apps.api.models import (
    AtsAlignmentResult,
    GapAnalysis,
    JobIntelligence,
    JobMatchResult,
    RequirementIntelligence,
    ResumeImprovement,
)
from services.eligibility.contracts import EligibilityResult
from services.job_discovery.sources.test_fixture import TEST_FIXTURE_SOURCE
from services.priority_ranking.engine import (
    ENGINE_VERSION as PRIORITY_ENGINE_VERSION,
    ORDERING as PRIORITY_ORDERING,
)


router = APIRouter(
    prefix="/jobs",
    tags=["jobs"],
)


def _get_visible_job_or_404(db: Session, job_id: str, current_user: User) -> Job:
    """The job, or the same 404 for a malformed id, a missing job, and
    another user's private submission (AJI-022) - so a private job's
    existence is never confirmed to anyone but its owner."""
    try:
        job_uuid = UUID(job_id)
    except ValueError:
        raise HTTPException(
            status_code=404,
            detail="Job not found",
        )

    job = get_visible_job(db, job_id=job_uuid, user_id=current_user.id)

    if job is None:
        raise HTTPException(
            status_code=404,
            detail="Job not found",
        )

    return job


def _job_to_response(job: Job, company_name: str | None) -> dict:
    return {
        "id": str(job.id),
        "title": job.title,
        "company": company_name,
        "location": job.location,
        "country": job.country,
        "remote_type": job.remote_type,
        "employment_type": job.employment_type,
        "salary_min": job.salary_min,
        "salary_max": job.salary_max,
        "salary_currency": job.salary_currency,
        "contract_duration": job.contract_duration,
        "contract_worker_type": job.contract_worker_type,
        "description": job.description,
        "requirements": job.requirements,
        "responsibilities": job.responsibilities,
        "posting_date": (
            job.posting_date.isoformat()
            if job.posting_date
            else None
        ),
        "source": job.source,
        # AJI-023 (Job Search): the provider's own id for this posting,
        # when it supplied one (null for submitted jobs and for providers
        # without stable ids). Never generated by NERO.
        "source_job_id": job.external_job_id,
        # AJI-024: lets the UI tell shared discovered jobs apart from the
        # caller's own private submissions (AJI-022), and flag synthetic
        # test-fixture jobs, without parsing `source` strings.
        "origin": (
            "user_submitted"
            if job.submitted_by_user_id is not None
            else "discovered"
        ),
        "is_test_data": job.source == TEST_FIXTURE_SOURCE,
        "source_url": job.source_url,
        "application_url": job.application_url,
        "first_seen_at": job.first_seen_at.isoformat(),
        "last_seen_at": job.last_seen_at.isoformat(),
    }


@router.get("")
def list_jobs(
    db: Session = Depends(get_db),
    # AJI-023 (Job Search): invalid criteria are a 422, never a silent
    # empty result - see apps/api/services/job_listing.py.
    search: str | None = Query(
        default=None, max_length=SEARCH_TEXT_MAX_LENGTH
    ),
    employment_type: EmploymentTypeFilter | None = Query(default=None),
    remote_type: RemoteTypeFilter | None = Query(default=None),
    location: str | None = Query(
        default=None, max_length=SEARCH_TEXT_MAX_LENGTH
    ),
    page: int = Query(default=1, ge=1),
    page_size: int = Query(default=20, ge=1, le=100),
    # Annotated so a direct Python call (existing tests) defaults to the
    # anonymous view instead of receiving the Depends marker itself.
    current_user: Annotated[
        User | None, Depends(get_optional_current_user)
    ] = None,
):
    # AJI-022 visibility + the optional filters, shared with the AJI-025
    # priority view so both scope jobs identically.
    query = job_listing_query(
        user_id=current_user.id if current_user is not None else None,
        search=search,
        employment_type=employment_type,
        remote_type=remote_type,
        location=location,
    )

    count_query = select(func.count()).select_from(
        query.subquery()
    )

    total = db.scalar(count_query) or 0

    offset = (page - 1) * page_size

    query = (
        query
        .order_by(
            Job.posting_date.desc().nullslast(),
            Job.id.asc(),
        )
        .offset(offset)
        .limit(page_size)
    )

    results = db.execute(query).all()

    jobs = [
        _job_to_response(job, company_name)
        for job, company_name in results
    ]

    return {
        "jobs": jobs,
        "pagination": {
            "page": page,
            "page_size": page_size,
            "total": total,
            "total_pages": (
                (total + page_size - 1) // page_size
                if total
                else 0
            ),
        },
    }


@router.post("/submissions")
def create_job_submission(
    payload: JobSubmissionRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Submit pasted job content (AJI-022) and analyze it synchronously.

    Creates a job private to the authenticated user (`source =
    "user_submitted"`), keeping the complete raw paste, then runs the
    existing Job Intelligence (AJI-012) and Requirement Intelligence
    (AJI-020A/B) pipelines on it. The pasted text is treated purely as
    untrusted job-description data. Resubmitting identical content reuses
    the same job rather than creating a duplicate, so retrying after a
    failed analysis is safe.

    No URL ingestion or scraping: only the pasted text is ever read.
    """
    try:
        result = submit_job(
            db,
            current_user=current_user,
            content=payload.content,
            title=payload.title,
            company=payload.company,
        )
    except JobSubmissionServiceError as exc:
        raise HTTPException(
            status_code=exc.status_code,
            detail={
                "message": str(exc),
                "job_id": str(exc.job_id) if exc.job_id else None,
            },
        ) from exc

    job = result.job
    company_name = job.company.name if job.company is not None else None

    return {
        "job": {
            **_job_to_response(job, company_name),
            "raw_submitted_content": job.raw_submitted_content,
        },
        "intelligence": _job_intelligence_to_response(
            result.job_intelligence
        ),
        "requirement_intelligence": _requirement_intelligence_to_response(
            result.requirement_intelligence
        ),
        "security": {
            "prompt_injection_detected": bool(result.injection_signals),
            "signals": [
                signal.model_dump() for signal in result.injection_signals
            ],
        },
    }


def _priority_item_to_response(item: PriorityItem) -> dict:
    result = item.result
    match = item.job_match
    ats = item.ats_alignment

    return {
        "job": _job_to_response(item.job, item.company_name),
        "rank": result.rank,
        "state": result.state.value,
        "eligibility_status": result.eligibility_status,
        "reasons": [
            {
                "code": reason.code,
                "source": reason.source,
                "kind": reason.kind,
                "message": reason.message,
            }
            for reason in result.reasons
        ],
        "blocking_factors": [
            {
                "code": factor.code,
                "source": factor.source,
                "message": factor.message,
            }
            for factor in result.blocking_factors
        ],
        # The exact inputs the ordering read, so a result can always be
        # traced to (and reconciled with) the job's own Match/ATS results.
        "inputs": {
            "eligibility": {
                "status": item.eligibility.status.value,
                "engine_version": item.eligibility.engine_version,
                "failed_constraints": item.eligibility.failed_constraints,
                "unknown_constraints": item.eligibility.unknown_constraints,
            },
            "job_match": (
                {
                    "id": str(match.id),
                    "score": match.score,
                    "confidence": match.confidence,
                    "engine_version": match.engine_version,
                    "job_intelligence_id": (
                        str(match.job_intelligence_id)
                        if match.job_intelligence_id
                        else None
                    ),
                    "current": result.job_match_current,
                    "created_at": match.created_at.isoformat(),
                }
                if match is not None
                else None
            ),
            "ats_alignment": (
                {
                    "id": str(ats.id),
                    "overall_score": ats.overall_score,
                    "confidence": ats.confidence,
                    "must_have_matched": ats.result.get("must_have_matched"),
                    "must_have_total": ats.result.get("must_have_total"),
                    "engine_version": ats.engine_version,
                    "requirement_intelligence_id": (
                        str(ats.requirement_intelligence_id)
                        if ats.requirement_intelligence_id
                        else None
                    ),
                    "current": result.ats_alignment_current,
                    "created_at": ats.created_at.isoformat(),
                }
                if ats is not None
                else None
            ),
        },
    }


# Declared before GET /{job_id} so "priority" is never read as a job id.
@router.get("/priority")
def get_job_priority(
    resume_version_id: str | None = Query(default=None),
    # AJI-023 (Job Search): invalid criteria are a 422, never a silent
    # empty result - see apps/api/services/job_listing.py.
    search: str | None = Query(
        default=None, max_length=SEARCH_TEXT_MAX_LENGTH
    ),
    employment_type: EmploymentTypeFilter | None = Query(default=None),
    remote_type: RemoteTypeFilter | None = Query(default=None),
    location: str | None = Query(
        default=None, max_length=SEARCH_TEXT_MAX_LENGTH
    ),
    page: int = Query(default=1, ge=1),
    page_size: int = Query(default=20, ge=1, le=100),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Order the authenticated user's analyzed jobs for their attention
    (AJI-025). Read-only and deterministic: it never calculates a missing
    analysis, never calls an AI provider, and never changes an
    application.

    Hard Eligibility (evaluated fresh) is a gate - an ineligible job is
    `excluded` and never ranked. The rest are ordered by Job Match, then
    ATS Alignment, for ONE resume version (`resume_version_id`, or the
    same default Job Match uses), then by the listing's own order. Job
    Match and ATS Alignment are never combined into one number; there is
    no priority score. A job with no Job Match for that version is
    `not_ready` and gets no rank.

    Only jobs this user has a Job Match or ATS Alignment for (for that
    resume version) are listed; the rest are counted in
    `counts.unanalyzed`. Uses the same visibility and filters as GET /jobs,
    so another user's private job can never appear. Personalized, so -
    unlike GET /jobs - it always requires authentication.
    """
    parsed_resume_version_id = _parse_optional_resume_version_id(
        resume_version_id
    )

    try:
        outcome = build_job_priority(
            db,
            current_user=current_user,
            resume_version_id=parsed_resume_version_id,
            search=search,
            employment_type=employment_type,
            remote_type=remote_type,
            location=location,
            page=page,
            page_size=page_size,
        )
    except PriorityRankingServiceError as exc:
        raise HTTPException(
            status_code=exc.status_code,
            detail=str(exc),
        ) from exc

    resume_version = outcome.resume_version

    return {
        "engine_version": PRIORITY_ENGINE_VERSION,
        "ordering": list(PRIORITY_ORDERING),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "user_id": str(current_user.id),
        "resume_version": (
            {
                "id": str(resume_version.id),
                "name": resume_version.name,
                "resume_filename": resume_version.resume.filename,
                "is_master": resume_version.is_master,
            }
            if resume_version is not None
            else None
        ),
        "counts": {
            **outcome.state_counts,
            "unanalyzed": outcome.unanalyzed_count,
        },
        "items": [
            _priority_item_to_response(item) for item in outcome.items
        ],
        "pagination": {
            "page": page,
            "page_size": page_size,
            "total": outcome.total,
            "total_pages": (
                (outcome.total + page_size - 1) // page_size
                if outcome.total
                else 0
            ),
        },
    }


@router.get("/{job_id}")
def get_job(
    job_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    A single job the authenticated user can see: any discovered job, or
    one of their own submitted jobs (AJI-022). Another user's submitted
    job 404s exactly like a job that does not exist.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    company_name = job.company.name if job.company is not None else None

    return {
        **_job_to_response(job, company_name),
        "raw_submitted_content": job.raw_submitted_content,
    }


def _job_match_to_response(match_record: JobMatchResult) -> dict:
    result_data = match_record.result

    return {
        "id": str(match_record.id),
        "job_id": str(match_record.job_id),
        "resume_version_id": str(match_record.resume_version_id),
        "job_intelligence_id": (
            str(match_record.job_intelligence_id)
            if match_record.job_intelligence_id
            else None
        ),
        "score": match_record.score,
        "confidence": match_record.confidence,
        "engine_version": match_record.engine_version,
        "strengths": result_data["strengths"],
        "skill_gaps": result_data["skill_gaps"],
        "components": result_data["components"],
        "must_have_matches": result_data["must_have_matches"],
        "must_have_gaps": result_data["must_have_gaps"],
        "preferred_matches": result_data["preferred_matches"],
        "preferred_gaps": result_data["preferred_gaps"],
    }


@router.get("/{job_id}/match")
def get_job_match(
    job_id: str,
    resume_version_id: str | None = Query(default=None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Return the authenticated user's most recently calculated Job Match
    for a job, without recomputing it (AJI-023). 404s when no match has
    been calculated yet (see POST /jobs/{job_id}/match).

    The read counterpart of the POST, like GET /ats and GET /gap-analysis:
    it lets the Jobs page show a job's existing Match next to its existing
    ATS Alignment and Gap Analysis instead of recalculating to see them.
    Job Match is user-specific - a user only ever reads their own rows.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)

    parsed_resume_version_id = _parse_optional_resume_version_id(
        resume_version_id
    )

    record = get_latest_job_match(
        db,
        user_id=current_user.id,
        job_id=job.id,
        resume_version_id=parsed_resume_version_id,
    )

    if record is None:
        raise HTTPException(
            status_code=404,
            detail="Job Match has not been calculated for this job yet.",
        )

    return _job_match_to_response(record)


@router.post("/{job_id}/match")
def calculate_job_match(
    job_id: str,
    resume_version_id: str | None = Query(default=None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Calculate and persist a deterministic Job Match Score for the
    authenticated user against a specific job.

    An explicit `resume_version_id` may be supplied to calculate the
    match against that exact ResumeVersion (it must belong to the
    authenticated user). When omitted, the existing default behavior
    applies: the user's most recent Resume, preferring its master
    ResumeVersion.
    """

    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    parsed_resume_version_id: UUID | None = None

    if resume_version_id is not None:
        try:
            parsed_resume_version_id = UUID(resume_version_id)
        except ValueError:
            raise HTTPException(
                status_code=404,
                detail="Resume version not found.",
            )

    try:
        match_record = calculate_job_match_service(
            db=db,
            current_user=current_user,
            job_id=job_uuid,
            resume_version_id=parsed_resume_version_id,
        )
    except JobMatchServiceError as exc:
        raise HTTPException(
            status_code=exc.status_code,
            detail=str(exc),
        ) from exc

    return _job_match_to_response(match_record)


def _eligibility_result_to_response(
    job_id: UUID,
    result: EligibilityResult,
    *,
    record_id: UUID,
    evaluated_at,
) -> dict:
    return {
        "id": str(record_id),
        "job_id": str(job_id),
        "status": result.status.value,
        "engine_version": result.engine_version,
        "checks": [
            {
                "constraint": check.constraint,
                "status": check.status.value,
                "reason": check.reason,
            }
            for check in result.checks
        ],
        "failed_constraints": result.failed_constraints,
        "unknown_constraints": result.unknown_constraints,
        "reasons": result.reasons,
        "evaluated_at": evaluated_at.isoformat(),
    }


@router.get("/{job_id}/eligibility")
def get_job_eligibility(
    job_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Evaluate deterministic Hard Eligibility (AJI-011) for the
    authenticated user against a specific job.

    This is intentionally separate from /jobs/{job_id}/match: eligibility
    is a hard pre-filter (ELIGIBLE/INELIGIBLE/UNKNOWN with explainable
    checks), never a score. The result is recalculated query-time from
    the user's current Preference/Profile and the job's current data, and
    then upserted into JobEligibilityResult (one row per user/job,
    overwritten in place) so a later AJI-012/AJI-013 consumer can read
    the job's current hard-eligibility status without recomputing it. See
    docs/ARCHITECTURE.md for the full hard-vs-soft rationale. Public job
    browsing (GET /jobs) never exposes this personalized data; this
    endpoint always requires authentication.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    result, record = evaluate_and_persist_job_eligibility(
        db=db,
        current_user=current_user,
        job=job,
    )

    return _eligibility_result_to_response(
        job.id,
        result,
        record_id=record.id,
        evaluated_at=record.updated_at,
    )


def _job_intelligence_to_response(record: JobIntelligence) -> dict:
    return {
        "id": str(record.id),
        "job_id": str(record.job_id),
        "content_fingerprint": record.content_fingerprint,
        "analysis_version": record.analysis_version,
        "analyzer_version": record.analyzer_version,
        "prompt_version": record.prompt_version,
        "model_provider": record.model_provider,
        "model_name": record.model_name,
        "extraction_status": record.extraction_status,
        "source": record.source,
        "source_url": record.source_url,
        "created_at": record.created_at.isoformat(),
        "intelligence": record.structured_intelligence,
    }


@router.get("/{job_id}/intelligence")
def get_job_intelligence(
    job_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Return the most recently computed Job Intelligence (AJI-012) snapshot
    for a job, without recomputing it. 404s when no snapshot has been
    generated yet (see POST /jobs/{job_id}/intelligence).

    Job Intelligence is shared, job-scoped data — never user-specific —
    but this endpoint still requires authentication like the rest of the
    per-job API surface, and never triggers an AI call on read.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    record = get_latest_job_intelligence(db, job_id=job_uuid)

    if record is None:
        raise HTTPException(
            status_code=404,
            detail="Job Intelligence has not been generated for this job yet.",
        )

    return _job_intelligence_to_response(record)


@router.post("/{job_id}/intelligence")
def create_job_intelligence(
    job_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Compute (or idempotently reuse) the Job Intelligence snapshot for a
    job. Reuses an existing snapshot when the job's observable content
    and the analyzer/prompt pipeline version are unchanged; otherwise
    produces a new, additional snapshot without overwriting history.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    try:
        record = generate_job_intelligence(db, job_id=job_uuid)
    except JobIntelligenceServiceError as exc:
        raise HTTPException(
            status_code=exc.status_code,
            detail=str(exc),
        ) from exc

    return _job_intelligence_to_response(record)


def _requirement_intelligence_to_response(record: RequirementIntelligence) -> dict:
    return {
        "id": str(record.id),
        "job_id": str(record.job_id),
        "content_fingerprint": record.content_fingerprint,
        "analysis_version": record.analysis_version,
        "analyzer_version": record.analyzer_version,
        "prompt_version": record.prompt_version,
        "model_provider": record.model_provider,
        "model_name": record.model_name,
        "extraction_status": record.extraction_status,
        "created_at": record.created_at.isoformat(),
        "intelligence": record.structured_intelligence,
    }


@router.get("/{job_id}/requirement-intelligence")
def get_requirement_intelligence(
    job_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Return the authenticated user's most recently computed Requirement
    Intelligence (AJI-020A/AJI-020B) snapshot for a job, without
    recomputing it. 404s when no snapshot has been generated yet (see
    POST /jobs/{job_id}/requirement-intelligence).

    Requirement Intelligence is persisted per-user (see
    apps/api/models.py's `RequirementIntelligence` docstring) — a user
    can only ever read their own snapshots, never another user's.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    record = get_latest_requirement_intelligence(
        db, user_id=current_user.id, job_id=job_uuid
    )

    if record is None:
        raise HTTPException(
            status_code=404,
            detail="Requirement Intelligence has not been generated for "
            "this job yet.",
        )

    return _requirement_intelligence_to_response(record)


@router.post("/{job_id}/requirement-intelligence")
def create_requirement_intelligence(
    job_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Compute (or idempotently reuse) the Requirement Intelligence
    (AJI-020A/AJI-020B) snapshot for the authenticated user against a
    job. Reuses an existing snapshot when the job's observable content,
    the analyzer/prompt pipeline version, and the configured AI
    provider/model are all unchanged; otherwise produces a new,
    additional snapshot without overwriting history.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    try:
        record = generate_requirement_intelligence(
            db, user_id=current_user.id, job_id=job_uuid
        )
    except RequirementIntelligencePersistenceError as exc:
        raise HTTPException(
            status_code=exc.status_code,
            detail=str(exc),
        ) from exc

    return _requirement_intelligence_to_response(record)


def _ats_alignment_to_response(record: AtsAlignmentResult) -> dict:
    result_data = record.result

    return {
        "id": str(record.id),
        "job_id": str(record.job_id),
        "resume_version_id": str(record.resume_version_id),
        "job_intelligence_id": str(record.job_intelligence_id),
        "requirement_intelligence_id": (
            str(record.requirement_intelligence_id)
            if record.requirement_intelligence_id
            else None
        ),
        "engine_version": record.engine_version,
        "overall_score": record.overall_score,
        "confidence": record.confidence,
        "scoring_version": result_data["scoring_version"],
        "must_have_total": result_data["must_have_total"],
        "must_have_matched": result_data["must_have_matched"],
        "preferred_total": result_data["preferred_total"],
        "preferred_matched": result_data["preferred_matched"],
        "must_have_ceiling": result_data.get("must_have_ceiling"),
        "score_components": result_data.get("score_components", []),
        "requirement_results": result_data["requirement_results"],
        # AJI-020C: descriptive-only, never scored - see
        # services/ats_alignment/contracts.py's
        # RequirementRelationshipGroup/ScreeningConstraintInfo docstrings.
        # `.get(..., [])` keeps a historical row persisted before this
        # migration (whose `result` JSON predates these keys) readable.
        "relationships": result_data.get("relationships", []),
        "screening_constraints": result_data.get("screening_constraints", []),
        "created_at": record.created_at.isoformat(),
    }


def _parse_optional_resume_version_id(
    resume_version_id: str | None,
) -> UUID | None:
    if resume_version_id is None:
        return None

    try:
        return UUID(resume_version_id)
    except ValueError:
        raise HTTPException(
            status_code=404,
            detail="Resume version not found.",
        )


@router.get("/{job_id}/ats")
def get_ats_alignment(
    job_id: str,
    resume_version_id: str | None = Query(default=None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Return the authenticated user's most recently computed ATS Alignment
    (AJI-013) result for a job, without recomputing it. 404s when no
    analysis has been generated yet (see POST /jobs/{job_id}/ats).

    ATS Alignment is user-specific (the same job can be analyzed against
    different resumes/users) — a user can only ever read their own
    results, never another user's.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    parsed_resume_version_id = _parse_optional_resume_version_id(
        resume_version_id
    )

    record = get_latest_ats_alignment(
        db,
        user_id=current_user.id,
        job_id=job_uuid,
        resume_version_id=parsed_resume_version_id,
    )

    if record is None:
        raise HTTPException(
            status_code=404,
            detail="ATS Alignment has not been generated for this job yet.",
        )

    return _ats_alignment_to_response(record)


@router.post("/{job_id}/ats")
def create_ats_alignment(
    job_id: str,
    resume_version_id: str | None = Query(default=None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Compute (or idempotently reuse) the ATS Alignment (AJI-013) result
    for the authenticated user against a specific job.

    An explicit `resume_version_id` may be supplied to align against
    that exact ResumeVersion (it must belong to the authenticated user).
    When omitted, the same default resume selection Job Match uses
    applies: the user's most recent Resume, preferring its master
    ResumeVersion.

    Reuses an existing result when the resume version, the underlying
    Job Intelligence snapshot, and the ATS engine version are all
    unchanged; otherwise produces a new, additional result without
    overwriting history.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    parsed_resume_version_id = _parse_optional_resume_version_id(
        resume_version_id
    )

    try:
        record = calculate_ats_alignment(
            db=db,
            current_user=current_user,
            job_id=job_uuid,
            resume_version_id=parsed_resume_version_id,
        )
    except ATSAlignmentServiceError as exc:
        raise HTTPException(
            status_code=exc.status_code,
            detail=str(exc),
        ) from exc

    return _ats_alignment_to_response(record)


def _gap_analysis_to_response(record: GapAnalysis) -> dict:
    return {
        "id": str(record.id),
        "job_id": str(record.job_id),
        "resume_version_id": str(record.resume_version_id),
        "job_intelligence_id": str(record.job_intelligence_id),
        "ats_alignment_id": str(record.ats_alignment_id),
        "analysis_version": record.analysis_version,
        "analyzer_version": record.analyzer_version,
        "prompt_version": record.prompt_version,
        "model_provider": record.model_provider,
        "model_name": record.model_name,
        "generation_status": record.generation_status,
        "must_have_gap_count": record.must_have_gap_count,
        "preferred_gap_count": record.preferred_gap_count,
        "gaps": record.result["gaps"],
        "created_at": record.created_at.isoformat(),
    }


@router.get("/{job_id}/gap-analysis")
def get_gap_analysis(
    job_id: str,
    resume_version_id: str | None = Query(default=None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Return the authenticated user's most recently computed Gap Analysis
    & Job-Specific Suggestions (AJI-015) result for a job, without
    recomputing it. 404s when no analysis has been generated yet (see
    POST /jobs/{job_id}/gap-analysis).

    Gap Analysis is user-specific, like ATS Alignment (the same job can
    be analyzed against different resumes/users) — a user can only ever
    read their own results, never another user's.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    parsed_resume_version_id = _parse_optional_resume_version_id(
        resume_version_id
    )

    record = get_latest_gap_analysis(
        db,
        user_id=current_user.id,
        job_id=job_uuid,
        resume_version_id=parsed_resume_version_id,
    )

    if record is None:
        raise HTTPException(
            status_code=404,
            detail="Gap Analysis has not been generated for this job yet.",
        )

    return _gap_analysis_to_response(record)


@router.post("/{job_id}/gap-analysis")
def create_gap_analysis(
    job_id: str,
    resume_version_id: str | None = Query(default=None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Compute (or idempotently reuse) the Gap Analysis & Job-Specific
    Suggestions (AJI-015) result for the authenticated user against a
    specific job.

    Every gap is read from the user's ATS Alignment (AJI-013) result for
    the same resume version — computing/reusing it first via the same
    resume-version resolution and idempotent caching
    POST /jobs/{job_id}/ats already uses, never a second, parallel
    requirement-alignment computation. Reuses an existing Gap Analysis
    result when the underlying ATS Alignment result and the analyzer/
    prompt pipeline version are all unchanged; otherwise produces a new,
    additional result without overwriting history.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    parsed_resume_version_id = _parse_optional_resume_version_id(
        resume_version_id
    )

    try:
        record = generate_gap_analysis(
            db=db,
            current_user=current_user,
            job_id=job_uuid,
            resume_version_id=parsed_resume_version_id,
        )
    except GapAnalysisServiceError as exc:
        raise HTTPException(
            status_code=exc.status_code,
            detail=str(exc),
        ) from exc

    return _gap_analysis_to_response(record)


def _resume_improvement_to_response(record: ResumeImprovement) -> dict:
    result_data = record.result

    return {
        "id": str(record.id),
        "job_id": str(record.job_id),
        "gap_analysis_id": str(record.gap_analysis_id),
        "baseline_ats_alignment_id": str(record.baseline_ats_alignment_id),
        "parent_resume_version_id": str(record.parent_resume_version_id),
        "child_resume_version_id": str(record.child_resume_version_id),
        "child_resume_version_name": result_data["child_resume_version_name"],
        "parent_resume_version_name": result_data.get(
            "parent_resume_version_name"
        ),
        "engine_version": record.engine_version,
        "approved_count": record.approved_count,
        "skipped_count": record.skipped_count,
        "recheck_status": record.recheck_status,
        "recheck_error": record.recheck_error,
        "recheck_ats_alignment_id": (
            str(record.recheck_ats_alignment_id)
            if record.recheck_ats_alignment_id
            else None
        ),
        "decisions": result_data["decisions"],
        # None whenever the recheck has not produced a result - the
        # created version is still reported in full above, since a failed
        # recheck never costs the user the version they approved.
        "comparison": result_data.get("comparison"),
        "created_at": record.created_at.isoformat(),
        "updated_at": record.updated_at.isoformat(),
    }


@router.get("/{job_id}/resume-improvement")
def get_resume_improvement(
    job_id: str,
    resume_version_id: str | None = Query(default=None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Return the authenticated user's most recent Resume Improvement
    Approval & Recheck record (AJI-021) for a job, without applying
    anything. 404s when the user has not approved any improvements for
    this job yet.

    This endpoint never creates a resume version, never re-runs Gap
    Analysis, and never calls the ATS engine - every one of those only
    ever happens from an explicit POST, because approval is the user's
    to give.

    The optional `resume_version_id` pins the lookup to improvements
    based on that exact parent version, mirroring the same parameter on
    /jobs/{job_id}/ats and /jobs/{job_id}/gap-analysis.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    parsed_resume_version_id = _parse_optional_resume_version_id(
        resume_version_id
    )

    record = get_latest_resume_improvement(
        db,
        user_id=current_user.id,
        job_id=job_uuid,
        parent_resume_version_id=parsed_resume_version_id,
    )

    if record is None:
        raise HTTPException(
            status_code=404,
            detail="No approved resume improvements for this job yet.",
        )

    return _resume_improvement_to_response(record)


@router.post("/{job_id}/resume-improvement")
def create_job_resume_improvement(
    job_id: str,
    payload: ResumeImprovementRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Apply the user's explicitly approved Gap Analysis suggestions
    (AJI-021): create a new child ResumeVersion from the approved,
    user-authored content and recheck it against this same job.

    Nothing here is automatic. The request must name an existing Gap
    Analysis result belonging to this user and carry an explicit
    approve/skip decision per suggestion; at least one approval is
    required, every approval must carry the user's own wording, and an
    `ADD_IF_TRUE` suggestion is only applied when the user confirmed it
    is accurate. The suggestion type is always read from the stored Gap
    Analysis row, so relabelling a gap in the request body cannot bypass
    that confirmation.

    The original resume version is never modified: the result is a new,
    additional version whose `parent_version_id` points back at it.
    Re-submitting the same approvals returns the existing record instead
    of creating a second version.

    This endpoint does NOT run the recheck. It returns with
    `recheck_status = "pending"`; running the recheck against the same
    job is a separate, explicit user action - POST
    /jobs/{job_id}/resume-improvement/{id}/recheck. The created version
    is already committed here, so it stays persisted and recoverable
    even if the recheck is never run.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    try:
        gap_analysis_uuid = UUID(payload.gap_analysis_id)
    except ValueError:
        raise HTTPException(
            status_code=404,
            detail="Gap Analysis not found.",
        )

    try:
        record = create_resume_improvement(
            db=db,
            current_user=current_user,
            job_id=job_uuid,
            gap_analysis_id=gap_analysis_uuid,
            decisions=[
                decision.model_dump() for decision in payload.decisions
            ],
        )
    except ResumeImprovementServiceError as exc:
        raise HTTPException(
            status_code=exc.status_code,
            detail={"code": exc.code, "message": str(exc)},
        ) from exc

    return _resume_improvement_to_response(record)


@router.post("/{job_id}/resume-improvement/{improvement_id}/recheck")
def retry_resume_improvement_recheck(
    job_id: str,
    improvement_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Run the recheck for an existing Resume Improvement record (AJI-021).

    This is both the initial "Run recheck" action after a version is
    created and the retry after a failure - one endpoint, because they
    do exactly the same thing. It rechecks the child version against the
    same job using the existing, unmodified ATS Alignment path.

    Never creates a resume version and never re-applies decisions - the
    version and the approvals are already durable. A record whose
    recheck already succeeded is returned unchanged rather than being
    re-scored, so the comparison the user was shown cannot silently
    change underneath them.
    """
    job = _get_visible_job_or_404(db, job_id, current_user)
    job_uuid = job.id

    try:
        improvement_uuid = UUID(improvement_id)
    except ValueError:
        raise HTTPException(
            status_code=404,
            detail="Resume improvement not found.",
        )

    try:
        record = run_recheck(
            db=db,
            current_user=current_user,
            job_id=job_uuid,
            improvement_id=improvement_uuid,
        )
    except ResumeImprovementServiceError as exc:
        raise HTTPException(
            status_code=exc.status_code,
            detail={"code": exc.code, "message": str(exc)},
        ) from exc

    return _resume_improvement_to_response(record)
