"""Helpers shared by the /jobs capability routers (AJI-034): the job
visibility check every per-job endpoint runs first, the job response
shape, and resume-version id parsing."""

from __future__ import annotations

from uuid import UUID

from fastapi import HTTPException
from sqlalchemy.orm import Session

from apps.api.models import Job, User
from apps.api.services.job_access import get_visible_job
from services.job_discovery.attribution import (
    attribution_link,
    get_source_attribution,
)
from services.job_discovery.sources.non_production import (
    is_non_production_source,
)


def _get_visible_job_or_404(db: Session, job_id: str, current_user: User) -> Job:
    """The job, or the same 404 for a malformed id, a missing job, and
    another user's private submission (AJI-022) - so a private job's
    existence is never confirmed to anyone but its owner."""
    try:
        job_uuid = UUID(job_id)
    except ValueError:
        raise HTTPException(
            status_code=404,
            detail="Job not found",
        )

    job = get_visible_job(db, job_id=job_uuid, user_id=current_user.id)

    if job is None:
        raise HTTPException(
            status_code=404,
            detail="Job not found",
        )

    return job


def _source_attribution_to_response(job: Job) -> dict | None:
    """AJI-028: how the UI must credit the job's source, from the generic
    attribution registry. None for a user's own submission and for any
    source without a registered attribution (e.g. the test fixture)."""
    if job.submitted_by_user_id is not None:
        return None

    attribution = get_source_attribution(job.source)

    if attribution is None:
        return None

    return {
        "name": attribution.display_name,
        "url": attribution_link(attribution, source_url=job.source_url),
        "requires_link_back": attribution.requires_link_back,
    }


def _job_to_response(job: Job, company_name: str | None) -> dict:
    return {
        "id": str(job.id),
        "title": job.title,
        "company": company_name,
        "location": job.location,
        "country": job.country,
        "remote_type": job.remote_type,
        "employment_type": job.employment_type,
        "salary_min": job.salary_min,
        "salary_max": job.salary_max,
        "salary_currency": job.salary_currency,
        "contract_duration": job.contract_duration,
        "contract_worker_type": job.contract_worker_type,
        "description": job.description,
        "requirements": job.requirements,
        "responsibilities": job.responsibilities,
        "posting_date": (
            job.posting_date.isoformat()
            if job.posting_date
            else None
        ),
        # AJI-028: provider-stated closing time (naive UTC), or null when
        # the provider stated none. Never inferred.
        "expires_at": (
            job.expires_at.isoformat()
            if job.expires_at
            else None
        ),
        "source": job.source,
        # AJI-028: generic source credit (display name, link, whether the
        # source's terms require the link to be shown) - see
        # services/job_discovery/attribution.py.
        "source_attribution": _source_attribution_to_response(job),
        # AJI-023 (Job Search): the provider's own id for this posting,
        # when it supplied one (null for submitted jobs and for providers
        # without stable ids). Never generated by NERO.
        "source_job_id": job.external_job_id,
        # AJI-024: lets the UI tell shared discovered jobs apart from the
        # caller's own private submissions (AJI-022), and flag synthetic
        # test-fixture jobs, without parsing `source` strings. AJI-030:
        # true for every synthetic source (fixture and development dataset).
        "origin": (
            "user_submitted"
            if job.submitted_by_user_id is not None
            else "discovered"
        ),
        "is_test_data": is_non_production_source(job.source),
        "source_url": job.source_url,
        "application_url": job.application_url,
        "first_seen_at": job.first_seen_at.isoformat(),
        "last_seen_at": job.last_seen_at.isoformat(),
    }


def _parse_optional_resume_version_id(
    resume_version_id: str | None,
) -> UUID | None:
    if resume_version_id is None:
        return None

    try:
        return UUID(resume_version_id)
    except ValueError:
        raise HTTPException(
            status_code=404,
            detail="Resume version not found.",
        )
