"""add gap analyses

Revision ID: 0a2b70df4b2d
Revises: 2b9a1d6e4f3c
Create Date: 2026-09-17 20:33:23.018558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a2b70df4b2d'
down_revision: Union[str, Sequence[str], None] = '2b9a1d6e4f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('resume_version_id', sa.UUID(), nullable=False),
    sa.Column('job_intelligence_id', sa.UUID(), nullable=False),
    sa.Column('ats_alignment_id', sa.UUID(), nullable=False),
    sa.Column('job_content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('analysis_version', sa.String(length=50), nullable=False),
    sa.Column('analyzer_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('generation_status', sa.String(length=20), nullable=False),
    sa.Column('must_have_gap_count', sa.Integer(), nullable=False),
    sa.Column('preferred_gap_count', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ats_alignment_id'], ['ats_alignment_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_intelligence_id'], ['job_intelligence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gap_analyses_ats_alignment_id'), 'gap_analyses', ['ats_alignment_id'], unique=False)
    op.create_index(op.f('ix_gap_analyses_job_content_fingerprint'), 'gap_analyses', ['job_content_fingerprint'], unique=False)
    op.create_index(op.f('ix_gap_analyses_job_id'), 'gap_analyses', ['job_id'], unique=False)
    op.create_index(op.f('ix_gap_analyses_job_intelligence_id'), 'gap_analyses', ['job_intelligence_id'], unique=False)
    op.create_index(op.f('ix_gap_analyses_resume_version_id'), 'gap_analyses', ['resume_version_id'], unique=False)
    op.create_index(op.f('ix_gap_analyses_user_id'), 'gap_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gap_analyses_user_id'), table_name='gap_analyses')
    op.drop_index(op.f('ix_gap_analyses_resume_version_id'), table_name='gap_analyses')
    op.drop_index(op.f('ix_gap_analyses_job_intelligence_id'), table_name='gap_analyses')
    op.drop_index(op.f('ix_gap_analyses_job_id'), table_name='gap_analyses')
    op.drop_index(op.f('ix_gap_analyses_job_content_fingerprint'), table_name='gap_analyses')
    op.drop_index(op.f('ix_gap_analyses_ats_alignment_id'), table_name='gap_analyses')
    op.drop_table('gap_analyses')
    # ### end Alembic commands ###
