"""add application tracking status and history

Revision ID: 359fa3edc371
Revises: e4ff8e1fc5fa
Create Date: 2026-09-18 12:13:25.491498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359fa3edc371'
down_revision: Union[str, Sequence[str], None] = 'e4ff8e1fc5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_status_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('saved_job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['saved_job_id'], ['saved_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('saved_jobs', sa.Column('applied_at', sa.DateTime(), nullable=True))
    op.add_column(
        'saved_jobs',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_unique_constraint('uq_saved_job_user_job', 'saved_jobs', ['user_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_saved_job_user_job', 'saved_jobs', type_='unique')
    op.drop_column('saved_jobs', 'updated_at')
    op.drop_column('saved_jobs', 'applied_at')
    op.drop_table('application_status_events')
    # ### end Alembic commands ###
