"""add resume ai analyses

Revision ID: 8084b6cd14ed
Revises: a6f4cbc0a2a0
Create Date: 2026-09-15 17:01:00.175191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8084b6cd14ed'
down_revision: Union[str, Sequence[str], None] = 'a6f4cbc0a2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_version_id', sa.UUID(), nullable=False),
    sa.Column('analysis_version', sa.String(length=50), nullable=False),
    sa.Column('analyzer_version', sa.String(length=50), nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_ai_analyses')
    # ### end Alembic commands ###
