"""add job intelligence

Revision ID: e838802968df
Revises: 847b3c9a4aaa
Create Date: 2026-09-17 15:05:13.313321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e838802968df'
down_revision: Union[str, Sequence[str], None] = '847b3c9a4aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_intelligence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('raw_jd_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('analysis_version', sa.String(length=50), nullable=False),
    sa.Column('analyzer_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('structured_intelligence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_intelligence_content_fingerprint'), 'job_intelligence', ['content_fingerprint'], unique=False)
    op.create_index(op.f('ix_job_intelligence_job_id'), 'job_intelligence', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_intelligence_job_id'), table_name='job_intelligence')
    op.drop_index(op.f('ix_job_intelligence_content_fingerprint'), table_name='job_intelligence')
    op.drop_table('job_intelligence')
    # ### end Alembic commands ###
