"""add job identity fingerprint

Revision ID: f9772d240f8e
Revises: 8084b6cd14ed
Create Date: 2026-09-16 14:04:06.443487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9772d240f8e'
down_revision: Union[str, Sequence[str], None] = '8084b6cd14ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('identity_fingerprint', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_jobs_identity_fingerprint'), 'jobs', ['identity_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_identity_fingerprint'), table_name='jobs')
    op.drop_column('jobs', 'identity_fingerprint')
    # ### end Alembic commands ###
